export CC := gcc
export PROJ_ROOT := $(realpath .)
export BUILD_DIR := build
TARGET_EXEC := brepviewer
OPTFLAGS := -O0 -ggdb
LIBS := glfw cglm GL m pthread Xrandr Xi dl
CFLAGS := -Ilib/include -Llib $(addprefix -l,$(LIBS)) $(OPTFLAGS)

SRCS := src/%.c
OBJS := $(BUILD_DIR)/$(notdir $(SRCS:.c=.o)) lib/%.o
# the generated dependency rules from the compiler
DEPS := $(BUILD_DIR)/$(notdir $(SRCS:.c=.d))

.PHONY: run
run: $(TARGET_EXEC)
	$(TARGET_EXEC)

$(TARGET_EXEC): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/%.o $(DEPS): $(SRCS)
	$(CC) -MP -MMD -c $^

lib/%.o:
	$(MAKE) -C lib/

